import * as forms from "codeforlife/components/form"
import { type FC } from "react"
import { Typography } from "@mui/material"

import { useCreateAuthFactorMutation } from "../../../../api/authFactor"

export interface SetupPendingProps {
  onSetup: () => void
}

const SetupPending: FC<SetupPendingProps> = ({ onSetup }) => {
  return (
    <>
      <Typography align="center" variant="h4" marginBottom={5}>
        Enable two-factor authentication
      </Typography>
      <>QRCode HERE</>
      <Typography>
        Alternatively you can use the following secret to manually set up TOTP
        in your authenticator or password manager.
      </Typography>
      <Typography>
        TOTP Secret: <span style={{ textDecoration: "underline" }}>ABC</span>
      </Typography>
      <Typography>Then, enter the token generated by the app.</Typography>
      <forms.Form
        initialValues={{ type: "otp" as const, otp: "" }}
        useMutation={useCreateAuthFactorMutation}
        submitOptions={{ then: onSetup }}
      >
        <forms.OtpField />
        <forms.SubmitButton sx={{ marginLeft: "auto" }}>
          Next
        </forms.SubmitButton>
      </forms.Form>
    </>
  )
}

export default SetupPending
