import env from "codeforlife/env"

export * from "codeforlife/env"

// Gmail.
export const GMAIL_FILTERS_PASSWORD_RESET_REQUEST =
  env.VITE_GMAIL_FILTERS_PASSWORD_RESET_REQUEST
export const GMAIL_FILTERS_EMAIL_VERIFICATION =
  env.VITE_GMAIL_FILTERS_EMAIL_VERIFICATION

// Links to external sites.
export const LINK_FEMALE_GRADUATES_IN_CS = env.VITE_LINK_FEMALE_GRADUATES_IN_CS
export const LINK_OUTLOOK_HOME = env.VITE_LINK_OUTLOOK_HOME
export const LINK_SKILLS_FOR_THE_FUTURE = env.VITE_LINK_SKILLS_FOR_THE_FUTURE
export const LINK_FACEBOOK = env.VITE_LINK_FACEBOOK
export const LINK_INSTAGRAM = env.VITE_LINK_INSTAGRAM
export const LINK_LINKEDIN = env.VITE_LINK_LINKEDIN
export const LINK_X = env.VITE_LINK_X
export const LINK_YOUTUBE = env.VITE_LINK_YOUTUBE
export const LINK_PORTAL_GITHUB = env.VITE_LINK_PORTAL_GITHUB
export const LINK_CFL_DOCS = env.VITE_LINK_CFL_DOCS
export const LINK_PRIMARY_PACK_GITBOOK = env.VITE_LINK_PRIMARY_PACK_GITBOOK
export const LINK_PRIMARY_PACK_DOWNLOAD = env.VITE_LINK_PRIMARY_PACK_DOWNLOAD
export const LINK_PYTHON_PACK_GITBOOK = env.VITE_LINK_PYTHON_PACK_GITBOOK
export const LINK_PYTHON_PACK_DOWNLOAD = env.VITE_LINK_PYTHON_PACK_DOWNLOAD
export const LINK_IMPACT_REPORT_2023 = env.VITE_LINK_IMPACT_REPORT_2023
export const LINK_IDEAS_BOX = env.VITE_LINK_IDEAS_BOX
export const LINK_HOME_LEARNING_BEGINNER = env.VITE_LINK_HOME_LEARNING_BEGINNER
export const LINK_HOME_LEARNING_INTERMEDIATE =
  env.VITE_LINK_HOME_LEARNING_INTERMEDIATE
export const LINK_HOME_LEARNING_ADVANCED = env.VITE_LINK_HOME_LEARNING_ADVANCED
