import env from "codeforlife/env"

export * from "codeforlife/env"

// Gmail.
export const GMAIL_FILTERS_PASSWORD_RESET_REQUEST =
  env.VITE_GMAIL_FILTERS_PASSWORD_RESET_REQUEST
export const GMAIL_FILTERS_EMAIL_VERIFICATION =
  env.VITE_GMAIL_FILTERS_EMAIL_VERIFICATION

// Links to external sites.
export const LINK_FEMALE_GRADUATES_IN_CS = env.VITE_LINK_FEMALE_GRADUATES_IN_CS
export const LINK_OUTLOOK_HOME = env.VITE_LINK_OUTLOOK_HOME
export const LINK_SKILLS_FOR_THE_FUTURE = env.VITE_LINK_SKILLS_FOR_THE_FUTURE
export const LINK_PORTAL_GITHUB = env.VITE_LINK_PORTAL_GITHUB
export const LINK_CFL_DOCS = env.VITE_LINK_CFL_DOCS
export const LINK_PRIMARY_PACK_GITBOOK = env.VITE_LINK_PRIMARY_PACK_GITBOOK
export const LINK_PRIMARY_PACK_DOWNLOAD = env.VITE_LINK_PRIMARY_PACK_DOWNLOAD
export const LINK_PYTHON_PACK_GITBOOK = env.VITE_LINK_PYTHON_PACK_GITBOOK
export const LINK_PYTHON_PACK_DOWNLOAD = env.VITE_LINK_PYTHON_PACK_DOWNLOAD
