import { vite } from "codeforlife/settings"

export * from "codeforlife/settings"

export const {
  // Gmail.
  GMAIL_FILTERS_PASSWORD_RESET_REQUEST,
  GMAIL_FILTERS_EMAIL_VERIFICATION,

  // Links to CFL docs.
  LINK_CFL_DOCS,
  LINK_CFL_DOCS_BECOME_A_CONTRIBUTOR,

  // Links to CFL GitHub.
  LINK_CFL_GH_WORKSPACE,

  // Links to GitBook content.
  LINK_GRASS_SNAKES_CLUB_PACK,
  LINK_TIGER_SNAKES_CLUB_PACK,
  LINK_COBRA_SNAKES_CLUB_PACK,

  // Links to CFL GitBook.
  // TODO: Restructure docs.
  LINK_PRIMARY_PACK_GITBOOK,
  LINK_PYTHON_PACK_GITBOOK,
  LINK_HOME_LEARNING_BEGINNER,
  LINK_HOME_LEARNING_INTERMEDIATE,
  LINK_HOME_LEARNING_ADVANCED,
  LINK_BLOCKLY_GUIDE,
  LINK_ENGLISH_CURRICULUM,
  LINK_SCOTTISH_CURRICULUM,

  // Links to GitBook files.
  LINK_IMPACT_REPORT_2023,
  LINK_IMPACT_REPORT_2024,
  LINK_OPPORTUNITIES_WITH_CFL,

  // Links to GitBook videos.
  LINK_TEACHING_RESOURCES_DEMO,
  LINK_RAPID_ROUTER_TEACHER_DEMO,
  LINK_PYTHON_DEN_DEMO,
  LINK_RAPID_ROUTER_STUDENT_DEMO,

  // Links to Google storage.
  LINK_PRIMARY_PACK_DOWNLOAD,

  // Links to Google forms.
  LINK_IDEAS_BOX,

  // Links to social media.
  LINK_FACEBOOK,
  LINK_INSTAGRAM,
  LINK_LINKEDIN,
  LINK_X,
  LINK_YOUTUBE,

  // Links to external sites.
  LINK_FEMALE_GRADUATES_IN_CS,
  LINK_OUTLOOK_HOME,
  LINK_SKILLS_FOR_THE_FUTURE,
} = vite
